const os = require('os');
console.log(os.type());
console.log(os.version());
console.log(os.freemem());
console.log(os.cpus());
console.log(os.arch());
console.log(os.homedir);
console.log(os.hostname());
console.log(os.totalmem());
console.log(os.totalmem);
